{
  const watchface = {
  width: 176, height: 152, bpp: 1, transparent: 0,
  buffer: E.toArrayBuffer(atob("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8fgAAB+H/4AAAAfgAAAAAAAAAAAAA/H4AAAfh//AAAAH4AAAAAAAAAAAAAPx+AAAH4f/4AAAB+AAAAAAAAAAAAAAcDgAAAOAAOAAAADgAAAAAAAAAAAAAHA4AAADgADgAAAA4AAAAAAAAAAAAABwOAAAA4AA4AAAAOAAAAAAAAAAAAAAcDgAAAOAAOAAAADgAAAAAAAAAAAAAHA4AAADg//gAAAA4AAAAAAAAAAAAABwOAAAA4f/wAAAAOAAAAAAAAAAAAAAcDgAAAOP/4AAAADgAAAAAAAAAAAAAHA4AAADjgAAAAAA4AAAAAAAAAAAAABwOAAAA44AAAAAAOAAAAAAAAAAAAAAcDgAAAOOAAAAAADgAAAAAAAAAAAAAHA4AAADjgAAAAAA4AAAAAAAAAAAAABwOAAAA4//4AAAAOAAAAAAAAAAAAAAcDgAAAOP/+AAAADgAAAAAAAAAAAAAHA4AAADj//gAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4D/4AAAAAAAAAAAAAAAAAAAAAAAAB+B//AAAAAAAAAAAAAAAAAAAAAAAAAfg//4AAAAAAAAAAAAAAAAAAAAAf/gA4eAPAAAAAAAAAAAAAAAAAAAAAH/8AOPAF4AAAAAAAAAAAAAAAAAAAAB//gDjgHuAAAAAAAAAAAAAAAAAAAAAAA4A44D7gAAAAAAAAAAAAAAAAAAAAAAOAOOD84AAAAAAAAAAAAAAAAAAAAAADgDjh8OAAAAAAAAAAAAAAAAAAAAAAA4A45+DgAAAAAAAAAAAAAAAAAAAAD/+AOO+A4AAAAAAAAAAAAAAAAAAAAB//ADjvAOAAAAAAAAAAAAAAAAAAAAA//gA49AHgAAAAAAAAAAAAAAAAAAAAOAAAOHgDwAAAAAAAAAAAAAAAAAAAADgAADg//4AAAAAAAAAAAAAAAAAAAAA4AAA4H/8AAAAAAAAAAAAAAAAAAAAAOAAAOA/+AAAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAD/+AP/wAAAAAAAAAAAAAAAAAAAAAAA//wH/+AAAAAAAAAAAAAAAAAAAAAAAP/+BwDwAAAAAAAAAAAAAAAAAAAAAAAAHgcAcAAAAAAAAAAAAAAAAAAAAAAAAA4HAHAAAAAAAAAAAPgAAAAAAAAAAAAOBwBwAAAAAAAAAAH8AAAAAAAAAAAADgf/8AAAAAAAAAABjAAAAAAAAAAA//4D//AAAAAAAAAAAYwAAAAAAAAAAP/+Af/wAAAAAAAAAAGMAAAAAAAAAAD//gAAcAAAAAAAAAAB/AAAAAAAAAAAAA4AAHAAAAAAAAAAAPgAAAAAAAAAAAAOAABwAAAAAAAAAAAAAAAAAAAAAAAADgAA8AAAAAAAAAAAAAAAAAAAAAAAAB4B/+AAAAAAAAAAAAAAAAAAAAAAAP/+Af/AAAAAAAAAAAAAAAAAAAAAAAD//AH/gAAAAAAAAAAAAAAAAAAAAAAA//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAAAAAAAAAOAOAf/AAAAAAAAAAAAAAAAAAAAAAADgDgH/wAAAAAAAAAAAAAAAAAAAAAAA4A4DweAAAAAAAAAAAAAAAAAAAAAAAOAOA4DgAAAAAAAAAAAAAAAAAAAAAADgDgOA4AAAAAAAAAAAAAAAAAAAAAAA4A4DweAAAAAAAAAAAAAAAAAAAAAAAOAOAf/AAAAAAAAAAAAAAAAAAAAAAAD//gP/4AAAAAAAAAAAAAAAAAAAAAAA//4H//AAAAAAAAAAAAAAAAAAAAAAAP/+BwBwAAAAAAAAAAAAAAAAAAAAAAAADgcAcAAAAAAAAAAAAAAAAAAAAAAAAA4HAHAAAAAAAAAAAAAAAAAAAAAAAAAOBwBwAAAAAAAAAAAAAAAAAAAAAAAADgf/8AAAAAAAAAAAAAAAAAAAAAAAAA4D/+AAAAAAAAAAAAAAAAAAAAAAAAAOAf/AAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAAAB/4AAAAf/4AAAAAAAAAAAAA//4AAAA/+AAAAH/+AAAAAAAAAAAAAP/+AAAAf/gAAAB//gAAAAAAAAAAAAAAPAAAAPAAAAAAcAAAAAAAAAAAAAAAADgAAADgAAAAAHAAAAAAAAAAAAAAAAB4AAAA4AAAAABwAAAAAAAAAAAAAAAA8AAAAOAAAAAAcAAAAAAAAAAAAAAAAPAAAAD/+AAAAH/8AAAAAAAAAAAAAAHgAAAA//wAAAA//gAAAAAAAAAAAAABwAAAAP/+AAAAH/8AAAAAAAAAAAAAA8AAAADgDgAAAAAHAAAAAAAAAAAAAAeAAAAA4A4AAAAABwAAAAAAAAAAAAAHgAAAAOAOAAAAAAcAAAAAAAAAAAAADwAAAADwDgAAAAAHAAAAAAAAAAAAAA4AAAAAf/4AAAB//wAAAAAAAAAAAAAeAAAAAD/8AAAAf/4AAAAAAAAAAAAAPAAAAAAf+AAAAH/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="))
};

  const rad = Math.PI / 180;
  const offset = [[-1,-2],[0,-2],[1,-2],[-2,-1],[-1,-1],[1,-1],[2,-1],[-2,0],[2,0],[-2,1],[-1,1],[1,1],[2,1],[-1,2],[0,2],[1,2]];

  g.clear();
  require("FontSinclair").add(Graphics);

  let drawTimeout;

  let drawhand = (angle,st,ed) => {
    let x = Math.cos(angle * rad);
    let y = Math.sin(angle * rad);
    x1 = 88 + x * st;
    y1 = 88 + 11 + y * st;
    x2 = 88 + x * ed;
    y2 = 88 + 11 + y * ed;
    for (let i = 0; i < offset.length; i++) {
      let ary = offset[i];
      g.drawLine(x1+ary[0], y1+ary[1], x2+ary[0], y2+ary[1]);
    }
    g.drawLine(88+x*4, 88+11+y*4, 88+x*st, 88+11+y*st);
  }

  let draw = () => {
    g.reset();
    g.clearRect(Bangle.appRect);
    g.drawImage(watchface, 0, 24);

    let currentDate = new Date();
    let hour = currentDate.getHours() % 12;
    let min = currentDate.getMinutes();
    let sec = currentDate.getSeconds();

    g.setFont("Sinclair");
    g.setFontAlign(0,0,0);
    g.drawString(currentDate.getFullYear(), 45, 105);
    g.drawString(require('locale').date(currentDate,0).substr(0,3).toUpperCase(), 45, 95);
    g.drawString(currentDate.getDate(), 130,105);
    g.drawString(require('locale').dow(currentDate).substr(0,3).toUpperCase(), 130, 95);
  
    drawhand((hour - 3) * 30 + min / 2, 12, 50);
    g.setColor(((g.getBgColor() & 0x7E0) ^ 0x7E0) | 0x1F);
    drawhand((min - 15) * 6, 12, 65);

    if (Bangle.isLocked()) {
      drawTimeout = setTimeout(draw, 60000 - Date.now() % 60000);
    } else {
      g.setColor(((g.getBgColor() & 0xFFE0) ^ 0xF800) | 0x1F);
      let sa = (sec - 15) * 6;
      let sx = Math.cos(sa * rad);
      let sy = Math.sin(sa * rad);
      g.drawLine(88+sx*4, 88+11+sy*4, 88+sx*70, 88+11+sy*70);
      drawTimeout = setTimeout(draw, 1000 - Date.now() % 1000);
    }
  }

  Bangle.on('lock', (on) => {
    if (!on) {
      if (drawTimeout) {
        clearTimeout(drawTimeout);
        drawTimeout = undefined;
      }
      draw();
    }
  });

  Bangle.setUI({
    mode : "clock",
    remove : function() {
      if (drawTimeout) {
        clearTimeout(drawTimeout);
      }
    }
  });

  Bangle.loadWidgets();
  draw();
  setTimeout(Bangle.drawWidgets,0);
}
